Set worker_processes to auto in nginx.conf
mecampbellsoup/nginx pull request #1
Opened 2021-09-03 16:48 UTC by mecampbellsoup

2021-09-03 16:49 UTC, salanki commented
No. We run multiple nginexes per node, you don't want each nginx to spin up a gazillion processes. It should stay at 1.

2021-09-03 16:56 UTC, mecampbellsoup commented
My argument is we should run one NGINX process w/ `n` workers instead. We don't need multiple NGINX master processes, that is extremely redundant and super inefficient as they all cache the same stuff in memory for their respective workers.

2021-09-08 14:12 UTC, kriscode1 requested changes
Nginx uses [sysconf(_SC_NPROCESSORS_ONLN)](https://www.man7.org/linux/man-pages/man3/sysconf.3.html) to detect the number of cores available. A quick test shows that this core count doesn't change even when inside a container with limited CPUs (that's a container-engine concept). So nginx will see 8 cores, for example, but may only have 100milliCPU of time. Reading the nginx docs above, it's best to set the requested resources of the pod to an integer number of CPUs and then set `worker_processes` to the same number.

2021-09-08 17:44 UTC, kriscode1 commented on entrypoint.sh
> +envsubst '${WORKER_PROCS}' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf
Nifty!

2021-09-09 14:20 UTC, kriscode1 approved these changes

2021-09-09 14:22 UTC, merged